name: Build
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  main:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "8.6"
          - "8.8"
          - "8.10"
          - "9.0"
          - "9.2"
          - "9.4"
          - "9.6"
          - "9.8"
          - "9.10"
        include:
        - os: macOS-latest
          ghc: "9.10"
        - os: windows-latest
          ghc: "9.10"
    steps:

    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"
        cabal-update: true

    - uses: actions/cache@v4
      name: Cache cabal store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Cabal version
      run: |
        cabal --version

    - name: Unpack
      run: |
        cabal sdist --ignore-project --output-directory ..
        cd ..
        cabal get atomic-counter-*.tar.gz -d default
        cabal get atomic-counter-*.tar.gz -d no-cmm

    - name: Build & Test default
      run: |
        project_file="$(pwd)/cabal.project.ci"

        cd ../default/atomic-counter-*/
        cabal build --project-file "$project_file" all
        cabal test --project-file "$project_file" --test-show-details=direct all
        cabal bench --project-file "$project_file" --benchmark-options='--stdev 100 --timeout 100' all

    - name: Haddock
      run: |
        cd ../default/atomic-counter-*/
        cabal haddock all

    - name: Cabal check
      run: |
        cd ../default/atomic-counter-*/
        cabal check

    - name: Build & Test no cmm
      run: |
        project_file="$(pwd)/cabal.project.ci"

        cd ../no-cmm/atomic-counter-*/
        cabal build --project-file "$project_file" --constraint "atomic-counter +no-cmm" all
        cabal test --project-file "$project_file" --constraint "atomic-counter +no-cmm" --test-show-details=direct all
        cabal bench --project-file "$project_file" --constraint "atomic-counter +no-cmm" --benchmark-options='--stdev 100 --timeout 100' all

  emulated:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ['armv7', 'aarch64']
    steps:
    - uses: actions/checkout@v4
    - uses: uraimo/run-on-arch-action@v3
      timeout-minutes: 60
      with:
        arch: ${{ matrix.arch }}
        distro: ubuntu_rolling
        githubToken: ${{ github.token }}
        install: |
          apt-get update -y
          apt-get install -y curl ghc cabal-install libghc-tasty-quickcheck-dev libghc-tasty-hunit-dev
        run: |
          project_file="$(pwd)/cabal.project.ci"
          cabal update
          cabal build --project-file "$project_file" --constraint "atomic-counter +no-cmm" all
          cabal test --project-file "$project_file" --constraint "atomic-counter +no-cmm" --test-show-details=direct all
          cabal bench --project-file "$project_file" --constraint "atomic-counter +no-cmm" --benchmark-options='--stdev 100 --timeout 100' all
